# Generated by Django 6.0.6 on 2026-07-02 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_hours_per_week',
            field=models.IntegerField(blank=True, help_text='Максимальная недельная нагрузка (только для преподавателей)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)], verbose_name='Макс. часов в неделю'),
        ),
    ]
