# Generated by Django 5.2.4 on 2026-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_max_hours_per_week'),
        ('school', '0002_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Дисциплины, которые может вести преподаватель', related_name='qualified_teachers', to='school.subject', verbose_name='Дисциплины'),
        ),
    ]
