# Generated by Django 5.2.15 on 2026-06-08 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('status', models.CharField(choices=[('pending', 'Запрошена'), ('confirmed', 'Подтверждена'), ('rejected', 'Отменена')], default='pending', max_length=10, verbose_name='Статус')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_initiated', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('new_teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_as_new', to=settings.AUTH_USER_MODEL, verbose_name='Новый преподаватель')),
                ('original_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='schedule.lesson', verbose_name='Исходное занятие')),
            ],
            options={
                'verbose_name': 'Замена',
                'verbose_name_plural': 'Замены',
                'ordering': ['-request_date'],
            },
        ),
    ]
